### PR TITLE
JENKINS-26854: Fix for not being able to start EC2 slaves after several hours

### PR DESCRIPTION
**Pull request by jjudd**
Hello all!

This pull request takes #131 and fixes the merge conflicts. @christ66 said the original PR looked good, but merge conflicts needed to be resolved. We ran into this issue after recently starting to use the plugin so we resolved the merge conflicts on #131.

Hope this is an appropriate way of going about this. My github-fu is weak. If opening another pull request is not appropriate, please let me know and I can accommodate.

Thanks!

### CODE REVIEW

**Comment by jjudd** [comment]
Looks like I forgot to finish resolving conflicts on one of the files and then resolved the conflict locally on a /target file rather than a /src file. Fixed :D

**Comment by christ66** [comment]
:+1:

**Comment by jjudd** [comment]
Want to mention here, as I did on the [bug report](https://issues.jenkins-ci.org/browse/JENKINS-26854) that when we ran into problems with this fix. The amazon api would start returning 429's because we were hitting the metadata service too frequently for instanceprofile credentials. Also, our jenkins server would become unresponsive after a few hours due to too many threads being started. 

I think I have a fix for this bug with [this commit](https://github.com/jjudd/ec2-plugin/commit/00f7cd963f37783c0e0cc50e76120ed2719ab24a). Put that on our jenkins server last night. If it's still working by end of day, I will create a PR. 

In the meantime, I would not merge this PR.

**Comment by francisu** [comment]
Closing per above comment. Noted, I just merged that smaller PR that fixed the two buttons.

**Pull request closed without merging**
