### PR TITLE
Support maximum builds on slave

### PR DESCRIPTION
**Pull request by GavrielNsof**

### CODE REVIEW

**Comment by francisu** [comment]
This replaces #223? If so, can you close that one?

**Comment by GavrielNsof** [comment]
@francisu Yes it replaces it, but I don't own #223 so I can't close it.
Sorry :)

**Comment by ariaviran** [comment]
@francisu 
Is there any chance to merge this?

**Comment by syl20bnr** [comment]
@francisu This is a very handy feature, we use it for months. Can be safely integrated in 1.40 IMO.

**Comment by thoulen** [comment]
Can you rebase ? and create a test for this feature ?

**Pull request closed without merging**
