### PR TITLE
JENKINS-26797 - Zombie instance created by the EC2 plugins

### PR DESCRIPTION
**Pull request by cbek**
* fixing error code for provisionOndemand - InvalidInstanceID.NotFound
* refactoring updateRemoteTags - no code duplication
* no exception throwing if remote tagging fails - only logging
** otherwise we got zombie instances which are not shown
* adding unit testing

https://issues.jenkins-ci.org/browse/JENKINS-26797

### CODE REVIEW

**Comment by cyrus-one** [comment]
thanks for this fix!

**Comment by cbek** [comment]
@francisu 
Can we merge this?
People waiting for fix: https://issues.jenkins-ci.org/browse/JENKINS-26797
I tested the fix on our live jenkins, problem seams to be fixed.
Today, I will prepare the change log, so that we can trigger the release of 1.27 :-)

**Comment by tjbaker** [comment]
I'd be great to get this in, thanks!

**Comment by daniel-beck** [comment]
This increases the visibility of `updateRemoteTags` for no apparent reason. Is this deliberate?

**Comment by cbek** [comment]
@daniel-beck 
What do you mean by increase the visibility of ```updateRemoteTags```?

The exception is now only logged, which will make sure that the new node/instance can be stored in jenkins config. Of course this means it can happen that instances miss tags in AWS, but this much better then having zombie instances.

**Comment by daniel-beck** [comment]
@cbek It used to be `private`, and now is `protected`. There is no obvious reason for that.

**Comment by cbek** [comment]
@daniel-beck 
Ok, agree.
Introduced powermock-module-junit4 for invokeMethod for testing private method.
I guess makes more sense now :-)

**Comment by cbek** [comment]
@francisu - Any concerns? Can we merge and release?

**Pull request merged**
