### PR TITLE
Add option to launch EBS-Optimized instances

### PR DESCRIPTION
**Pull request by kunickiaj**
Adds a check box to allow for launching EBS-Optimized slaves.
Bumps aws sdk from 1.10.0 to 1.10.2

Wasn't sure about the appropriate formatting as there seems to be a mix :)

```
Results :

Tests run: 53, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:52 min
[INFO] Finished at: 2015-07-02T10:50:07-07:00
[INFO] Final Memory: 54M/445M
[INFO] ------------------------------------------------------------------------
```

### CODE REVIEW

**Comment by francisu** [comment]
Would you mind removing the formatting changes from this? I just took a pull request that cleaned up the formatting, this request should only show functionality that has changed. Thanks!

**Comment by kunickiaj** [comment]
Will do.

**Comment by kunickiaj** [comment]
Don't really understand what's going on with these jenkins builds.. Any tips on what may be up here?

**Comment by jravetch** [comment]
@francisu Any update?  Would like to see this merged.  Thanks

**Comment by kunickiaj** [comment]
Should be good to merge unless I've overlooked something.

**Comment by francisu** [comment]
Thanks for your contribution!

**Comment by jravetch** [comment]
@francisu Nice!  Will we see a new release of the plugin soon?

**Comment by francisu** [comment]
I can do a release tomorrow if you want. Can you validate that your new
feature is working in the snapshot and let me know, then I will release it?

On Mon, Jul 27, 2015 at 7:46 PM, jravetch <notifications@github.com> wrote:

> @francisu <https://github.com/francisu> Nice! Will we see a new release
> of the plugin soon?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jenkinsci/ec2-plugin/pull/153#issuecomment-125416438>.
>



-- 
Cell 510 432 1589

**Comment by jravetch** [comment]
@kunickiaj Can you please verify?

**Comment by kunickiaj** [comment]
Will do. Worked fine when I submitted it but I'll re-verify in a bit.

**Pull request merged**
