### PR TITLE
Only periodically call internalCheck in EC2RetentionStrategy.

### PR DESCRIPTION
**Pull request by jzyeezy**
Co-authored-by: Adrien Tateno <adrien.k.tateno@gmail.com>

## What is happening
We have scenarios where Jenkins needs to provision many new worker nodes on the scale of 100+ machines. See corresponding [Jira ticket](https://issues.jenkins-ci.org/browse/JENKINS-57161) detailing the observed behavior. After profiling Jenkins, we observed that as the EC2 instances spin up, let's say 60 of them, those instances' futures may finish during a single call to `NodeProvisioner.update()`. `Jenkins.updateComputerList` is then called for every instance that finishes, which calls `EC2RetentionStrategy.check()` for _every_ computer known to Jenkins, resulting in ~3000 synchronous AWS API calls and a multi-100 second lock for a single invocation of `NodeProvisioner.update()`. When this lock is held during `NodeProvisioner.update()`, the queue's `maintain` method cannot be invoked, which also requires this very lock to proceed.

This issue manifests in the following ways:
1. The UI's build queue is not responsive when you try to kick off or kill a build while the locks are present 
2. No buildable queue items are being assigned to the growing list of available idle agents
3. Once `NodeProvisioner.update()` relinquishes its hold on the queue lock, the build queue flushes and assigns all the work to the available agents. This can take anywhere from 10-20 minutes with our stress tests. 

We can nicely illustrate this behavior with a build simulation where we kick off a build that has 100 parallel steps, each with a sleep of 24 minutes. Our cloud's machines are configured to have 1 executor per machine:
Screen Shot 2019-05-03 at 10 38 14 AM

## Our solution
This PR helps alleviate the duration that `EC2RetentionStrategy.check()` holds the queue lock by avoiding the high I/O cost in repeatedly hitting the AWS EC2 API for a single node. Because of `internalCheck`'s 1 min return value, it appears this method is designed such that it doesn't need to be called every time. Our solution takes that return value into account and keeps track of the last time `internalCheck` was called. It should only be called once a minute rather than checking every computer, every time a new node is added. We observed that the amount of time that the queue is locked substantially decreases to 1 minute and work is assigned out of the queue to the available agents much faster.
Screen Shot 2019-05-03 at 10 41 07 AM

### CODE REVIEW

**Comment by jzyeezy** [comment]
@jvz no problem, thanks for the read! is anything else needed in order to merge this PR?

**Comment by jzyeezy** [comment]
Or maybe @thoulen could help with merging?

**Comment by jvz** [comment]
Back from vacation.

**Comment by jmcampanini** [comment]
i just built the plugin from trunk and ran into an issue with the clock being a non-whitelisted class. my guess is that the clock doesnt need to be serialized/persisted?

here's the stacktrace:

```
Provisioned agent EC2 (EC2 Slaves) - ubuntu16.04 m4.xlarge failed to launch
java.lang.UnsupportedOperationException: Refusing to marshal java.time.Clock$SystemClock for security reasons; see https://jenkins.io/redirect/class-filter/
	at hudson.util.XStream2$BlacklistedTypesConverter.marshal(XStream2.java:542)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
	at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:263)
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:250)
Caused: java.lang.RuntimeException: Failed to serialize hudson.plugins.ec2.EC2RetentionStrategy#clock for class hudson.plugins.ec2.EC2RetentionStrategy
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:254)
	at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:222)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
	at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:208)
	at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:149)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
	at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:263)
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:250)
Caused: java.lang.RuntimeException: Failed to serialize hudson.model.Slave#retentionStrategy for class hudson.plugins.ec2.EC2OndemandSlave
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:254)
	at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:222)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
	at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:208)
	at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:149)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
	at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:82)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1026)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1015)
	at com.thoughtworks.xstream.XStream.toXML(XStream.java:988)
	at hudson.XmlFile.write(XmlFile.java:193)
Caused: java.io.IOException
	at hudson.XmlFile.write(XmlFile.java:200)
	at jenkins.model.Nodes.persistNode(Nodes.java:180)
	at jenkins.model.Nodes.addNode(Nodes.java:145)
	at jenkins.model.Jenkins.addNode(Jenkins.java:2085)
	at hudson.slaves.NodeProvisioner$2.run(NodeProvisioner.java:241)
	at hudson.model.Queue._withLock(Queue.java:1379)
	at hudson.model.Queue.withLock(Queue.java:1256)
	at hudson.slaves.NodeProvisioner.update(NodeProvisioner.java:208)
	at hudson.slaves.NodeProvisioner.access$000(NodeProvisioner.java:62)
	at hudson.slaves.NodeProvisioner$NodeProvisionerInvoker.doRun(NodeProvisioner.java:806)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:72)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Pull request merged**
