### PR TITLE
Use AWS credentials to manage the IAM access key

### PR DESCRIPTION
**Pull request by cyrille-leclerc**
Use centralized AWS credentials to manage the IAM access key in the Jenkins Credentials Store and allow to reuse the credentials in other plugins, help auditing configuration changes... (See screenshot 1)

Additional enhancement: if no IAM Credentials have been defined, use the standard AWS credentials resolution mechanism (see [DefaultAWSCredentialsProviderChain](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.html) and screenshot 2):
 * Environment Variables - `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` (RECOMMENDED since they are recognized by all the AWS SDKs and CLI except for .NET), or `AWS_ACCESS_KEY` and `AWS_SECRET_KEY` (only recognized by Java SDK)
 * Java System Properties - aws.accessKeyId and aws.secretKey
 * Credential profiles file at the default location (~/.aws/credentials) shared by all AWS SDKs and the AWS CLI
 * Instance profile credentials delivered through the Amazon EC2 metadata service (IAM role defined at the ec2 instance level)

Note: this PR is based on PR #173 

### Screenshot 1: Jenkins EC2 Plugin - AWS credentials support

Jenkins EC2 Plugin with AWS credentials

### Screenshot 2: Jenkins EC2 Plugin - AWS credentials resolution

Jenkins EC2 Plugin - AWS credentials resolution

### CODE REVIEW

**Comment by cyrille-leclerc** [comment]
cc @abayer

**Comment by abayer** [comment]
This replaces #173, right? Also, cc @reviewbybees. =)

**Comment by cyrille-leclerc** [comment]
@abayer I preferred to split in 2 PRs to separate the topics but yes, as https://github.com/jenkinsci/ec2-plugin/pull/174 contains the commit of https://github.com/jenkinsci/ec2-plugin/pull/173, we can say that it replaces the previous PR.

**Comment by abayer** [comment]
Yeah, that was what I was wondering about. I'd say go ahead and merge #173 then.

**Comment by stephenc** [comment]
what's the status here

**Comment by cyrille-leclerc** [comment]
Hello @francisu, did you have time to look at this Pull Request? Do you want any additional detail?

**Comment by francisu** [comment]
@cyrille-leclerc hi, I have not yet had a chance to look at this, as I have been working on fixing bugs so that I can get a bugfix release done. Once that's done I will have a look at this. Do you mind fixing it to merge correctly with the now-current code?

**Comment by cyrille-leclerc** [comment]
@francisu thanks, I'll merge the changes

**Comment by cyrille-leclerc** [comment]
@francisu merged and tested.

**Comment by kmadel** [comment]
@cyrille-leclerc Definitely a good addition to allow more central management of the secure config info. Looking forward to this getting merged!

**Comment by cbsmith** [comment]
Wanted to poke on the status of this pull request...

**Comment by johnnyshields** [comment]
@cyrille-leclerc pull request is conflicted now.

**Comment by vnadgir-ef** [comment]
@cyrille-leclerc: Great stuff!! 

@francisu
We would really love to see this feature released and available to use.
I see that this PR has conflicts currently. Can you provide an ETA for this?

We can offer to help out if that speeds up the adoption of this PR.

**Comment by francisu** [comment]
Thanks for the offer of help. If you could fix the conflicts and retest it that would be helpful.

**Comment by cyrille-leclerc** [comment]
PR replaced by https://github.com/jenkinsci/ec2-plugin/pull/194

**Pull request closed without merging**
