### PR TITLE
[JENKINS-61304] Fixes a case when a node temporarily offline would be terminated by the plugin

### PR DESCRIPTION
**Pull request by unicolet**
Fixes: https://issues.jenkins-ci.org/browse/JENKINS-61304

### CODE REVIEW

**Comment by unicolet** [comment]
checking ci failures, seems relevant

**Comment by unicolet** [comment]
not sure what's wrong. Reproducing locally yields failures when launching `mvn clean install` from console, while running the single unit test from Idea just works. Looks like tests all fail on ssh auth:

```
  39.014 [id=66]	INFO	hudson.plugins.ec2.EC2Cloud#log: Connected via SSH.
  39.274 [id=66]	WARNING	hudson.plugins.ec2.EC2Cloud#log: Exception trying to authenticate
java.io.IOException: Cannot read full block, EOF reached.
	at com.trilead.ssh2.crypto.cipher.CipherInputStream.getBlock(CipherInputStream.java:81)
	at com.trilead.ssh2.crypto.cipher.CipherInputStream.read(CipherInputStream.java:108)
	at com.trilead.ssh2.transport.TransportConnection.receiveMessage(TransportConnection.java:232)
	at com.trilead.ssh2.transport.TransportManager.receiveLoop(TransportManager.java:706)
	at com.trilead.ssh2.transport.TransportManager$1.run(TransportManager.java:502)
Caused: java.io.IOException: The connection is closed.
	at com.trilead.ssh2.auth.AuthenticationManager.deQueue(AuthenticationManager.java:72)
	at com.trilead.ssh2.auth.AuthenticationManager.getNextMessage(AuthenticationManager.java:100)
	at com.trilead.ssh2.auth.AuthenticationManager.authenticatePublicKey(AuthenticationManager.java:277)
Caused: java.io.IOException: Publickey authentication failed.
	at com.trilead.ssh2.auth.AuthenticationManager.authenticatePublicKey(AuthenticationManager.java:302)
	at com.trilead.ssh2.Connection.authenticateWithPublicKey(Connection.java:451)
	at hudson.plugins.ec2.ssh.EC2UnixLauncher.bootstrap(EC2UnixLauncher.java:331)
	at hudson.plugins.ec2.ssh.EC2UnixLauncher.launchScript(EC2UnixLauncher.java:160)
	at hudson.plugins.ec2.EC2ComputerLauncher.launch(EC2ComputerLauncher.java:48)
	at hudson.slaves.SlaveComputer$1.call(SlaveComputer.java:294)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I'm out of my depth here :-(

**Comment by unicolet** [comment]
@res

**Comment by unicolet** [comment]
@res0nance any chance you would have some time  to check this? Thanks!

**Comment by AbdulRahmanAlHamali** [comment]
Hey @unicolet , we have some Jenkins jobs that are hanging while waiting for their nodes that suddenly went offline:
```
12:42:42  Cannot contact EC2 (coveodev) - Linux Docker Build QA (i-008532094c18f10da): hudson.remoting.ChannelClosedException: Channel "hudson.remoting.Channel@2a2fc020:EC2 (coveodev) - Linux Docker Build QA (i-008532094c18f10da)": Remote call on EC2 (coveodev) - Linux Docker Build QA (i-008532094c18f10da) failed. The channel is closing down or has closed down
```

Do you think this is the cause of that issue?

**Comment by unicolet** [comment]
@AbdulRahmanAlHamali what plugin version are you running? I think the latest version is pretty solid

I'm seeing the problem that this PR tries to fix because we run a maintenance job on the node fleet every hour. This job cleans up workspaces, etc and to avoid it interfere with build we set the node temporarily offline. Unless you have a similar setup I would say your problem seems unrelated.

Maybe you're using spot instances and the instance has been reclaimed by EC2?

**Comment by AbdulRahmanAlHamali** [comment]
Indeed, I just found out the Jenkins instances having the issues are not up-to-date. I'll try updating them and seeing if that fixes the issue

**Pull request closed without merging**
