### PR TITLE
Test case for the PR296

### PR DESCRIPTION
**Pull request by janario**
https://github.com/jenkinsci/ec2-plugin/pull/296

### CODE REVIEW

**Comment by thoulen** [comment]
The 296 needs to be rebased

**Comment by janario** [comment]
296 was started by @JamesXNelson

But he was not able to create the test case at the time, that's why I've sent this PR just for the test case
https://github.com/jenkinsci/ec2-plugin/pull/296#issuecomment-488773080

I was thinking about someone resolve the conflicts while merging it
Or we can see with him if he can take a look

**Comment by jvz** [comment]
Newly added test failed in CI?

**Comment by janario** [comment]
Ok, so what I have done:

This was initially just the test case for https://github.com/jenkinsci/ec2-plugin/pull/296

I've pulled the changes from the other PR to maintain the author of it and because he could was not able to take a look on it https://github.com/jenkinsci/ec2-plugin/pull/296#issuecomment-488773080, 

I've re-based his changes with the latest master and added my change(test-case) on it. He still as the author of the contribution/commit

Let me know if it is all right

Thanks :-)

**Comment by janario** [comment]
Awesome, Thanks ;-) :+1:

**Pull request merged**
