### PR TITLE
JENKINS-32915

### PR DESCRIPTION
**Pull request by jjudd**
Cleaning up the PR in #186 so it can be merged and the issue can be closed.

### CODE REVIEW

**Comment by jjudd** [comment]
I haven't checked this on our Jenkins. I am in the process of doing that. If anything breaks, I will update accordingly.

**Comment by francisu** [comment]
@jjudd Thanks James, I will wait until you check it before I merge it.

**Comment by jjudd** [comment]
No problems so far. Things seem to be fine.

**Comment by johnnyshields** [comment]
:+1: lets get this one merged. The current state is pretty nasty, I was quite surprised when I had launched 20 c4 larges!!!

**Comment by johnnyshields** [comment]
@francisu can we get a release for this?

**Pull request merged**
