### PR TITLE
[JENKINS-72007] Support new AWS machine types

### PR DESCRIPTION
**Pull request by MarkEWaite**
## [JENKINS-72007] Support new AWS machine types

[JENKINS-72007](https://issues.jenkins.io/browse/JENKINS-72007) asks for support of new EC2 instance types that are available with newer versions of the AWS Java SDK.  I'm not a user of the AWS Java SDK, but there is a release of the new version of the API plugin that provides the new machine types.

### Current pre-release

* [EC2 pre-release from this pull request](https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/ec2/1645.ve11a_2de7a_188/ec2-1645.ve11a_2de7a_188.hpi) depends on the released versions of [SDK minimal](https://plugins.jenkins.io/aws-java-sdk-minimal/releases/#version_1.12.586-413.v6a_6c3a_420126) and [SDK EC2](https://plugins.jenkins.io/aws-java-sdk-ec2/releases/#version_1.12.586-413.v6a_6c3a_420126).

### Testers verified earlier versions

* [SDK minimal](https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/aws-java-sdk/aws-java-sdk-minimal/1.12.582-407.vc9d39d85d5f6/aws-java-sdk-minimal-1.12.582-407.vc9d39d85d5f6.hpi) - or find the [most recent pull request](https://github.com/jenkinsci/aws-java-sdk-plugin/pulls?q=is%3Apr+is%3Aopen+bump+revision+from)
* [SDK EC2](https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/aws-java-sdk/aws-java-sdk-ec2/1.12.582-407.vc9d39d85d5f6/aws-java-sdk-ec2-1.12.582-407.vc9d39d85d5f6.hpi)  - or find the [most recent pull request](https://github.com/jenkinsci/aws-java-sdk-plugin/pulls?q=is%3Apr+is%3Aopen+bump+revision+from)
* [EC2](https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/ec2/1638.v634f699a_7b_45/ec2-1638.v634f699a_7b_45.hpi)

Includes or supersedes the following pull requests:

* #907 
* #906
* #903
* #902
* #901
* #900
* #897
* #896
* #881
* #876

### Testing done

Confirmed that automated tests pass. No interactive testing

### Submitter checklist
* [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
* [x] Ensure that the pull request title represents the desired changelog entry
* [x] Please describe what you did
* [x] Link to relevant issues in GitHub or Jira
* [x] Link to relevant pull requests, esp. upstream and downstream changes

### CODE REVIEW

**Comment by damentz** [comment]
Can confirm this works, was able to use the C7a8xlarge to complete a package build for Arch Linux.  Runtime went from 12 minutes to 7 minutes by switching from C6a8xlarge to C7a8xlarge.

Master Controller: Jenkins v2.429 with JDK 11
Build Node:

```
INFO: Verifying: java -fullversion
openjdk full version "17.0.8+7-Debian-1deb12u1"
...
<===[JENKINS REMOTING CAPACITY]===>Remoting version: 3181.v78543a_987053
```

**Comment by mytxyang** [comment]
Hi, "SDK minimal" and "SDK EC2" binary cannot download now, could you please provider new address?
When can we release this change? We need create Jenkins Dynamic Instance for M7A type soon.

**Comment by MarkEWaite** [comment]
> Hi, "SDK minimal" and "SDK EC2" binary cannot download now, could you please provider new address? When can we release this change? We need create Jenkins Dynamic Instance for M7A type soon.

As my time allows, I'll try to provide an updated version of the SDK plugins and the EC2 plugin.  

If your organization depends on prompt releases of the EC2 plugin, you should volunteer to help maintain the plugin.  That will give you permissions to release new versions and deliver the features that you need and will help the community.

**Comment by MarkEWaite** [comment]
> Hi, "SDK minimal" and "SDK EC2" binary cannot download now, could you please provider new address? When can we release this change? We need create Jenkins Dynamic Instance for M7A type soon.

I've updated the links for [SDK minimal](https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/aws-java-sdk/aws-java-sdk-minimal/1.12.582-407.vc9d39d85d5f6/aws-java-sdk-minimal-1.12.582-407.vc9d39d85d5f6.hpi) and [SDK EC2](https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/aws-java-sdk/aws-java-sdk-ec2/1.12.582-407.vc9d39d85d5f6/aws-java-sdk-ec2-1.12.582-407.vc9d39d85d5f6.hpi) in the pull request description so that they now point to persistent locations.  

My earlier comments still apply:

> If your organization depends on prompt releases of the EC2 plugin, you should volunteer to help maintain the plugin. That will give you permissions to release new versions and deliver the features that you need and will help the community.

**Comment by MarkEWaite** [comment]
@res0nance , @fcojfernandez , @MRamonLeon , @thoulen , or @froblesmartin this has been tested in earlier earlier iterations with good results.  Would you be willing to merge and release a new version so that users can access the most recent machine types?

**Review by res0nance — APPROVED** [review]

**Pull request merged**
