### PR TITLE
Use AWS credentials to manage the IAM access key

### PR DESCRIPTION
**Pull request by cyrille-leclerc**
Use centralized AWS credentials to manage the IAM access key in the Jenkins Credentials Store and allow to reuse the credentials in other plugins, help auditing configuration changes... (See screenshot 1)

Additional enhancement: if no IAM Credentials have been defined, use the standard AWS credentials resolution mechanism (see [DefaultAWSCredentialsProviderChain](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.html) and screenshot 2):
 * Environment Variables - `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` (RECOMMENDED since they are recognized by all the AWS SDKs and CLI except for .NET), or `AWS_ACCESS_KEY` and `AWS_SECRET_KEY` (only recognized by Java SDK)
 * Java System Properties - aws.accessKeyId and aws.secretKey
 * Credential profiles file at the default location (~/.aws/credentials) shared by all AWS SDKs and the AWS CLI
 * Instance profile credentials delivered through the Amazon EC2 metadata service (IAM role defined at the ec2 instance level)

Note: this PR is based on PR #173 

### Screenshot 1: Jenkins EC2 Plugin - AWS credentials support

Jenkins EC2 Plugin with AWS credentials

### Screenshot 2: Jenkins EC2 Plugin - AWS credentials resolution

Jenkins EC2 Plugin - AWS credentials resolution

### CODE REVIEW

**Comment by johnnyshields** [comment]
@francisu please merge :)

**Comment by johnnyshields** [comment]
@cyrille-leclerc I believe this PR may have broken spot instance price checking.

image

Everything else, including launching spot instance, seems to work fine. Stack trace here: https://gist.github.com/johnnyshields/df4fe7ed2a85c417653f77be7eabdec9

**Comment by johnnyshields** [comment]
@cyrille-leclerc AMI check also does not work

image

**Comment by francisu** [comment]
Maybe we should back this one out until everything works? If it can be fixed in the next day or so that would be fine. @johnnyshields what do you think?

**Comment by johnnyshields** [comment]
Let's wait for a response from @cyrille-leclerc, I imagine it's a straightforward fix. If no response in 24h yes let's backout.

**Comment by cyrille-leclerc** [comment]
I just discovered your message. I'll investigate today.

**Comment by francisu** [comment]
Thanks @cyrille-leclerc as soon as we get your fixes, we will test and then release the plugin. Can you do your further corrections in a separate pull request?

**Comment by cyrille-leclerc** [comment]
@francisu I fixed the 2 buttons in https://github.com/jenkinsci/ec2-plugin/pull/198 /cc @johnnyshields

**Comment by francisu** [comment]
Thanks, @johnnyshields can you have a look and merge it if it's right and then I will release.

**Pull request merged**
