### PR TITLE
[JENKINS-71737] rename cloudName to name

### PR DESCRIPTION
**Pull request by car-roll**
Preparing for https://github.com/jenkinsci/jenkins/pull/8310 where cloud name changes will be done on a separate page

The use of the variable name cloudName in AmazonEC2Cloud forces jenkins core to have a special case of handling cloudName when it not a variable of Cloud.
https://github.com/jenkinsci/jenkins/blob/d41b0f5807923286ad33d4847af95e2c6c7c77ba/core/src/main/java/jenkins/agents/CloudSet.java#L229

### Testing done
manually created new AmazonEC2Cloud
test in config-as-code integration tests: https://github.com/jenkinsci/configuration-as-code-plugin/pull/2372/

```[tasklist]
### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by car-roll** [comment]
All tests pass locally, and manual testing works fine. I'm not sure why I'm seeing a specific issue here in the CasC integration tests: https://github.com/jenkinsci/configuration-as-code-plugin/pull/2372/#issuecomment-1718707873

**Comment by car-roll** [comment]
Sorry @res0nance would you mind taking a look at another PR? Related to https://github.com/jenkinsci/jenkins/pull/8310

This is upstream of #891

**Comment by car-roll** [comment]
This would need a release as well to support https://github.com/jenkinsci/configuration-as-code-plugin/pull/2372

**Review by res0nance — APPROVED** [review]

**Comment by nick-ax** [comment]
I can confirm that this is a breaking change for CasC 😢

**Pull request merged**
