### PR TITLE
Support maximum builds on slave

### PR DESCRIPTION
**Pull request by ariaviran**
Added support to set a maximum number of builds on a slave before it is
terminated in a setting called 'Maximum Total Uses'.

Resolves JENKINS-8618
Related to PR #162

### CODE REVIEW

**Comment by ariaviran** [comment]
@johnnyshields 
As discussed [here](https://github.com/jenkinsci/ec2-plugin/pull/162#issuecomment-233664778), found the time to implement this based on PR #162 .

I didn't implement the 'restart after N **failures**' but this can be added later on top of this work.

**Comment by GavrielNsof** [comment]
@ariaviran May I ask if this PR discarded? Is there a workaround for this?

**Comment by LuisPiedra** [comment]
This seems a quite interesting addition... 

Can I contribute to solve the conflicts?  I'm not sure if I can contribute to this PR or if I need to open a new PR.

**Comment by ariaviran** [comment]
@GavrielNsof 
This plugin wasn't actively developed for a very long time so this PR just stayed open. I use a self-built version of the plugin with the code from this PR in my Jenkins setup for quite some time now without any hiccups, but if you want to go down that road I suggest you do it with caution.

@LuisPiedra 
I see this project is active again - feel free to use the code here and open a new PR without conflicts, I'm afraid I can't invest the time to work on this

**Comment by GavrielNsof** [comment]
@LuisPiedra @ariaviran I think I will start developing this.
Hopefully it will be merged after I'm done.

**Comment by GavrielNsof** [comment]
New PR - https://github.com/jenkinsci/ec2-plugin/pull/249

I hope it will be merged soon. Please help and review :)

**Comment by GavrielNsof** [comment]
and thanks @ariaviran for the code

**Comment by GavrielNsof** [comment]
@ariaviran Please close this pull request - I have a new one #269
Thanks for all the help :)

**Pull request closed without merging**
