### PR TITLE
JENKINS-48548: Add T2 Unlimited Support

### PR DESCRIPTION
**Pull request by rsennewald**
- Added configuration option for templates to select T2 Unlimited.

### CODE REVIEW

**Comment by jvz** [comment]
Can you rebase this from master? This plugin got some new maintainers recently and we're looking to clear up the backlog. Thanks!

**Comment by derschatta** [comment]
yeah it would be great to see this patch being merged and released, kind of waiting for it ;)

**Comment by rsennewald** [comment]
rebased for your merging pleasure!

**Comment by rsennewald** [comment]
Should I merge this or will you @jvz ?

**Pull request merged**
