### PR TITLE
JENKINS-46294: Allow block reservations for spot instances

### PR DESCRIPTION
**Pull request by nullify005**
What it says on the tin, allows for the setting of a Spot Block when requesting a spot instance so that you get your instance for at least that duration.

https://issues.jenkins-ci.org/browse/JENKINS-46294

### CODE REVIEW

**Comment by thoulen** [comment]
Can you resolve the conflicts ?

**Comment by nullify005** [comment]
done, @thoulen

**Comment by nullify005** [comment]
Something I'm not quite fond of now is the branching structure for spot instances introduced by the useBidPrice boolean.
It feels like there's code duplication here for not a lot of reason - however I'm not going to tackle that here

**Comment by thoulen** [comment]
Thanks, for the work.
The spot instance support wasn't a first citizen in the plugin until now that start to be one of the most critical function. It needs a deep refactor, probably for the 1.50 I will adjust.

**Pull request merged**
