### PR TITLE
Use AWS4SignerType instead of QueryStringSignerType

### PR DESCRIPTION
**Pull request by leeor**
This solved the authorization problem with the eu-central-1 region.
Have also bumped the AWS SDK version.

### CODE REVIEW

**Comment by baldzern4** [comment]
Hi,
this fix worked for me. I am now able to use eu-central-1.
Can someone @francisu - include this pull request?
Thanks,

**Comment by francisu** [comment]
Do we know how this affects the other regions?

**Comment by leeor** [comment]
I test the connection through the settings section to every other AWS region (didn't have the key pair defined in each region, but the test was able to connect and communicate well enough to figure that out.

**Comment by francisu** [comment]
Thanks very much for your help on this!

**Pull request merged**
