### PR TITLE
Check more places where passing a null instanceID can do a search of random spot instances. 

### PR DESCRIPTION
**Pull request by jjrussell**
and clean up Some other NPEs

These are additional fixes related to https://github.com/jenkinsci/ec2-plugin/pull/106 that I found after submitting the PR. We have these running in production and haven't seen any problems related to the original report since.

### CODE REVIEW

**Comment by jjrussell** [comment]
@andyleclair @maudineormsby @rob-lane @kchard @jlogsdon @miketotheg

**Comment by andyleclair** [comment]
this looks legit, but it's been a minute since I wrote java, so I feel shaky giving my stamp of approval

**Comment by maudineormsby** [comment]
Same story as @andyleclair; the logic seems correct.

**Comment by francisu** [comment]
Thanks for your contribution!

**Comment by jjrussell** [comment]
Thanks for the merge. Looking forward to getting back on the upstream version on the next release.

**Pull request merged**
