### PR TITLE
add instance type dl1

### PR DESCRIPTION
**Pull request by sg3629**
add support for instance type dl1

### CODE REVIEW

**Comment by sg3629** [comment]
@jvz need some help in review and adding image type to support dl1 images.

**Comment by jvz** [comment]
Hello! I'm not maintaining this plugin anymore (I typically use EKS directly and deploy what I need to there). @res0nance are you still using this plugin?

**Comment by sg3629** [comment]
@jvz thank you!
@res0nance  can you help with the review and merge to support dl1 instance type?

**Review by res0nance — APPROVED** [review]

**Comment by sg3629** [comment]
thank you @res0nance ! 
can you help in merging this PR as well?

**Comment by res0nance** [comment]
> thank you @res0nance ! can you help in merging this PR as well?

There's a compiler error either the label name is wrong or the ec2-api is not up to date enough.
So I can't merge it until this issue is resolved

**Comment by sg3629** [comment]
@res0nance ,
any suggestion on what can be done to update ec2-api or adding label>?

**Comment by sg3629** [comment]
@res0nance not sure why the Jenkins check is failing for the above. can someone help here?

**Comment by sg3629** [comment]
recheck

**Comment by sg3629** [comment]
@res0nance any update on this PR and/or jenkins failure?

**Comment by sg3629** [comment]
@res0nance  can help merge this now?

**Pull request merged**
