### PR TITLE
Fix connection strategy warning for new templates

### PR DESCRIPTION
**Pull request by res0nance**
Edge case missed in #538 

- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your master branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by radnov** [comment]
@res0nance Thanks for the quick reaction! 

Note that there are a few more usages of `toString()`, like [here](https://github.com/jenkinsci/ec2-plugin/pull/626/files#diff-2569749802877edc1d4e6fb86580ac97ae86dda6ddfc31d85807032b4200cec9R2050)  and the following lines.

Would these also be a candidate for change? 

I'm reproducing [this issue](https://github.com/jenkinsci/ec2-plugin/pull/538#issuecomment-824561251) mentioned by @jensenbox with the following steps:

1. Apply/reload JCasC configuration for the EC2 plugin containing `connectionStrategy` key for an AMI template
2. Run a pipeline targeting the agent specified with the AMI template label

The result is an ERROR after the Jenkins Master tries to establish an SSH connection to the agent:
```
ERROR: Unexpected error in launching an agent. This is probably a bug in Jenkins
java.lang.NullPointerException
	at java.base/java.lang.ProcessEnvironment.validateValue(ProcessEnvironment.java:120)
	at java.base/java.lang.ProcessEnvironment$Value.valueOf(ProcessEnvironment.java:203)
	at java.base/java.lang.ProcessEnvironment$StringEnvironment.put(ProcessEnvironment.java:243)
	at java.base/java.lang.ProcessEnvironment$StringEnvironment.put(ProcessEnvironment.java:221)
	at hudson.slaves.CommandLauncher.launch(CommandLauncher.java:141)
	at hudson.plugins.ec2.ssh.EC2UnixLauncher.launchScript(EC2UnixLauncher.java:264)
	at hudson.plugins.ec2.EC2ComputerLauncher.launch(EC2ComputerLauncher.java:48)
	at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:294)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:80)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by res0nance** [comment]
> EC2UnixLauncher

That error looks like you have remoteFS null?

**Comment by radnov** [comment]
Yep, the `remoteFS` field/key was indeed the issue. It wasn't set to `null`, but instead wasn't part of the configuration loaded with JCasC at all. I've set it to an empty string `remoteFS: ""` and the NullPointerException is gone. Thank you! 🚀 

Still, the current PR fixes a relevant issue with the UI complaining about the `connectionStrategy` value.

**Comment by fasatrix** [comment]
@res0nance did you test with windows EC2 workers? it seems to have broke our set up.

From Jenkins logs:

`Failed to verify connectivity to Windows agent
java.net.NoRouteToHostException: No route to host (Host unreachable)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at hudson.plugins.ec2.win.WinConnection.pingFailingIfSSHHandShakeError(WinConnection.java:124)
	at hudson.plugins.ec2.win.EC2WindowsLauncher.connectToWinRM(EC2WindowsLauncher.java:189)
	at hudson.plugins.ec2.win.EC2WindowsLauncher.launchScript(EC2WindowsLauncher.java:52)
	at hudson.plugins.ec2.EC2ComputerLauncher.launch(EC2ComputerLauncher.java:48)
	at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:294)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:80)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)`
	
from the plugin logs:

`
EC2 (win-base-worker) - windows worker (i-0c7938fd70697fe96) booted at 1622754173000
Invalid host (null or 0.0.0.0). Your host is most likely waiting for an IP address.
Waiting for WinRM to come up. Sleeping 10s.
Invalid host (null or 0.0.0.0). Your host is most likely waiting for an IP address.
Waiting for WinRM to come up. Sleeping 10s.
`

**Comment by res0nance** [comment]
> @res0nance did you test with windows EC2 workers? it seems to have broke our set up.
> 
> From Jenkins logs:
> 
> `Failed to verify connectivity to Windows agent java.net.NoRouteToHostException: No route to host (Host unreachable) at java.base/java.net.PlainSocketImpl.socketConnect(Native Method) at java.base/java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source) at java.base/java.net.SocksSocketImpl.connect(Unknown Source) at java.base/java.net.Socket.connect(Unknown Source) at hudson.plugins.ec2.win.WinConnection.pingFailingIfSSHHandShakeError(WinConnection.java:124) at hudson.plugins.ec2.win.EC2WindowsLauncher.connectToWinRM(EC2WindowsLauncher.java:189) at hudson.plugins.ec2.win.EC2WindowsLauncher.launchScript(EC2WindowsLauncher.java:52) at hudson.plugins.ec2.EC2ComputerLauncher.launch(EC2ComputerLauncher.java:48) at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:294) at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46) at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:80) at java.base/java.util.concurrent.FutureTask.run(Unknown Source) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at java.base/java.lang.Thread.run(Unknown Source)`
> 
> from the plugin logs:
> 
> `EC2 (win-base-worker) - windows worker (i-0c7938fd70697fe96) booted at 1622754173000 Invalid host (null or 0.0.0.0). Your host is most likely waiting for an IP address. Waiting for WinRM to come up. Sleeping 10s. Invalid host (null or 0.0.0.0). Your host is most likely waiting for an IP address. Waiting for WinRM to come up. Sleeping 10s.`

This change is entirely UI related only.

What was the version before this that worked for you?

**Comment by radnov** [comment]
@res0nance Seems like this got worse 🤔 

From [this comment](https://github.com/jenkinsci/ec2-plugin/pull/538#issuecomment-854471671)
> This is more broken now with 1.60 than before. I literally tried every possible combination of fields but the connection strategy always falls back to "Public DNS".

image

**Comment by res0nance** [comment]
> @res0nance Seems like this got worse 🤔
> 
> From [this comment](https://github.com/jenkinsci/ec2-plugin/pull/538#issuecomment-854471671)
> 
> > This is more broken now with 1.60 than before. I literally tried every possible combination of fields but the connection strategy always falls back to "Public DNS".
> 
> image

I replied in that thread https://github.com/jenkinsci/ec2-plugin/pull/538#issuecomment-854537937

**Comment by fasatrix** [comment]
> > @res0nance did you test with windows EC2 workers? it seems to have broke our set up.
> > From Jenkins logs:
> > `Failed to verify connectivity to Windows agent java.net.NoRouteToHostException: No route to host (Host unreachable) at java.base/java.net.PlainSocketImpl.socketConnect(Native Method) at java.base/java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source) at java.base/java.net.SocksSocketImpl.connect(Unknown Source) at java.base/java.net.Socket.connect(Unknown Source) at hudson.plugins.ec2.win.WinConnection.pingFailingIfSSHHandShakeError(WinConnection.java:124) at hudson.plugins.ec2.win.EC2WindowsLauncher.connectToWinRM(EC2WindowsLauncher.java:189) at hudson.plugins.ec2.win.EC2WindowsLauncher.launchScript(EC2WindowsLauncher.java:52) at hudson.plugins.ec2.EC2ComputerLauncher.launch(EC2ComputerLauncher.java:48) at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:294) at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46) at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:80) at java.base/java.util.concurrent.FutureTask.run(Unknown Source) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at java.base/java.lang.Thread.run(Unknown Source)`
> > from the plugin logs:
> > `EC2 (win-base-worker) - windows worker (i-0c7938fd70697fe96) booted at 1622754173000 Invalid host (null or 0.0.0.0). Your host is most likely waiting for an IP address. Waiting for WinRM to come up. Sleeping 10s. Invalid host (null or 0.0.0.0). Your host is most likely waiting for an IP address. Waiting for WinRM to come up. Sleeping 10s.`
> 
> This change is entirely UI related only.
> 
> What was the version before this that worked for you?

1.59 was the one that worked. We have a process in place that automatically build a new jenkis  image with latest version of plugin used and this morning we found out that 1.60 broke our windows workers and some weird behaviour with Linux one too but fixable with workaround. I too get get the error related to connection strategy highlighed.abive

**Pull request merged**
