### PR TITLE
[JENKINS-35457] Migrate from using bouncy castle to bouncycastle-api plugin

### PR DESCRIPTION
**Pull request by alvarolobato**
[JENKINS-35457](https://issues.jenkins-ci.org/browse/JENKINS-35457)
Dependency to multiple Bouncy Castle versions from jenkins core and plugins is causing problems due to the binary incompatibility between versions, the different supported algorithms, etc.

Plugins should be migrated to use a common API and BC version in order to avoid these problems, see [bouncycastle-api plugin](https://github.com/jenkinsci/bouncycastle-api/blob/master/README.md)

@reviewbybees

### CODE REVIEW

**Comment by johnnyshields** [comment]
:+1: fine by me. @francisu

**Comment by rsandell** [comment]
:bee:

**Comment by recena** [comment]
🐝

**Comment by recena** [comment]
@reviewbybees done

**Comment by alvarolobato** [comment]
@johnnyshields I consider this PR is ready to be merged. If you agree it would be great if you could release a new version. Thanks.

**Comment by recena** [comment]
@francisu Thanks so much! Do you plan to cut a new release?

**Comment by francisu** [comment]
Sure, I can do that in the next couple of days.

**Comment by recena** [comment]
@francisu This would be great!

**Comment by francisu** [comment]
We did this, but then we got this bug filed: https://issues.jenkins-ci.org/browse/JENKINS-36197  Can someone look into this? I don't have the time right now. If it can't be addressed in a couple of days, I will need to revert this one, as I hate having a broken current release out there.

**Comment by johnnyshields** [comment]
@alvarolobato can you help with JENKINS-36197 ?

**Comment by alvarolobato** [comment]
Just responded on the Jira Issue.

**Pull request merged**
