### PR TITLE
[JENKINS-43677] Update AWS SDK to 1.11.119

### PR DESCRIPTION
**Pull request by burdandrei**
To add I3 instances added in 1.11.96
Waiting for https://github.com/jenkinsci/aws-java-sdk-plugin/pull/11 to work

### CODE REVIEW

**Comment by stevematyas** [comment]
+1

**Comment by burdandrei** [comment]
@stevematyas SDK plugin update was merged and  published, so just update SDK plugin in your jenkins instance, and you'll receive new instances.

**Comment by francisu** [comment]
Please remove the update to the ec2-plugin version; this is not the right way to do that. Also, see: https://github.com/jenkinsci/ec2-plugin/pull/231 for problems I had building with the new SDK. Any help would be appreciated.

**Comment by burdandrei** [comment]
sorry for silence @francisu, I updated SDK itself and received new instance type,i can see that in #231 you sorted the issue, so it's your call to merge or not to merge it.

**Comment by francisu** [comment]
I took #231 which does this.

**Pull request closed without merging**
