### PR TITLE
[JENKINS-33339] Allow root volumes to be deleted on termination

### PR DESCRIPTION
**Pull request by medwards**
Fixes [JENKINS-33339](https://issues.jenkins-ci.org/browse/JENKINS-33339)

### CODE REVIEW

**Comment by medwards** [comment]
Some things for me to do still:
* Get it to pass unit tests (still not sure how to get this to work locally)
* Verify the UI hooks actually work (Its my first time exposing things to the user)
* Run it in a real environment

If you don't merge beforehand I'll ping y'all when I'm done.

**Comment by medwards** [comment]
It looks like it should be working, but the volume still seems incorrectly marked:
```
No existing instance found - created new instance: {InstanceId: i-88548f05,ImageId: ***,State: {Code: 0,Name: pending},PrivateDnsName: ***,PublicDnsName: ,StateTransitionReason: ,KeyName: vagrant,AmiLaunchIndex: 0,ProductCodes: [],InstanceType: r3.xlarge,LaunchTime: Tue Sep 06 18:51:52 CEST 2016,Placement: {AvailabilityZone: eu-west-1b,GroupName: ,Tenancy: default,},Monitoring: {State: disabled},SubnetId: ***,VpcId: ***,PrivateIpAddress: ***,StateReason: {Code: pending,Message: pending},Architecture: x86_64,RootDeviceType: ebs,RootDeviceName: /dev/xvda,BlockDeviceMappings: [],VirtualizationType: hvm,ClientToken: ***,Tags: [],SecurityGroups: [{GroupName: ***,GroupId: ***}],SourceDestCheck: true,Hypervisor: xen,NetworkInterfaces: [{NetworkInterfaceId: ***,SubnetId: ***,VpcId: ***,Description: ,OwnerId: ***,Status: in-use,MacAddress: ***,PrivateIpAddress: ****,PrivateDnsName: ***,SourceDestCheck: true,Groups: [{GroupName: ***,GroupId: ***}],Attachment: {AttachmentId: eni-attach-b36cc06c,DeviceIndex: 0,Status: attaching,AttachTime: Tue Sep 06 18:51:52 CEST 2016,DeleteOnTermination: true},PrivateIpAddresses: [{PrivateIpAddress: ***,PrivateDnsName: ***,Primary: true,}]}],IamInstanceProfile: {Arn: ***,Id: ***},EbsOptimized: false,}
```

**Comment by medwards** [comment]
Ack, turns out even after I resolve a settings persistence bug this doesn't work the way I think it does. I'll experiment a bit.

**Comment by medwards** [comment]
I also change `setupEphemeralDeviceMapping` and `setupCustomDeviceMapping` to operate on the device mapping list in the launch specification or run instances request. There's now only one method signature and they append to the list rather than wiping it out.

This also means we can support ephemeral *and* custom device mapping at the same time now. I'm not sure who has this use-case and it seems like a dramatic change so I didn't include it here.

**Comment by medwards** [comment]
We're using the snapshot of this internally now and it looks good.

**Comment by medwards** [comment]
OK, just got back from vacation and am happy to report no leaked volumes and our environment is still stable ^^

**Comment by johnnyshields** [comment]
Looks good to me! @francisu what do you think?

**Comment by medwards** [comment]
I've rebased the branch as we got hit by JENKINS-38481 and didn't have it in our custom build of ec2-plugin.

**Comment by micahlmartin** [comment]
In addition to this, is there a way to configure the size of the root volume or am I just missing it?

**Comment by medwards** [comment]
I didn't include anything for it. I assumed it was fixed, at least by instance type.

**Pull request merged**
