### PR TITLE
Jenkins 19059/ssh launcher for spot instance

### PR DESCRIPTION
**Pull request by francisu**

### CODE REVIEW

**Comment by ikikko** [comment]
:+1: 

Thanks for sending a pull request!

**Comment by francisu** [comment]
I will clean this up to handle only the issue about polling for the SSH launcher for windows, also making this an option. The other commits related spot issues won't be part of this.

**Comment by ikikko** [comment]
Yes, you are right.

The first commit a020b7c7f486cd50a759a346e6df72fdd773e3dd is a essential one for this issue, and the others are not.

**Comment by francisu** [comment]
I think #179 takes care of this.

**Pull request closed without merging**
