### PR TITLE
JENKINS-26414 - Add support for new C4 instance types

### PR DESCRIPTION
**Pull request by cbek**
* upgrade aws-java-sdk ot version 1.9.24

https://issues.jenkins-ci.org/browse/JENKINS-26414

### CODE REVIEW

**Comment by francisu** [comment]
Thanks for your contribution!

**Comment by nexus49** [comment]
Experiencing authentication issues with the updated sdk version when provisioning a computer: 

```
com.amazonaws.AmazonServiceException: AWS was not able to validate the provided access credentials (Service: AmazonEC2; Status Code: 401; Error Code: AuthFailure; Request ID: cbe99ae9-fb3b-45c1-a4e7-3c3e79c939b5)
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1078)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:726)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:461)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:296)
	at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:10549)
	at com.amazonaws.services.ec2.AmazonEC2Client.describeKeyPairs(AmazonEC2Client.java:7218)
	at com.amazonaws.services.ec2.AmazonEC2Client.describeKeyPairs(AmazonEC2Client.java:10193)
	at hudson.plugins.ec2.EC2PrivateKey.find(EC2PrivateKey.java:135)
	at hudson.plugins.ec2.SlaveTemplate.getKeyPair(SlaveTemplate.java:722)
	at hudson.plugins.ec2.SlaveTemplate.provisionSpot(SlaveTemplate.java:546)
	at hudson.plugins.ec2.SlaveTemplate.provision(SlaveTemplate.java:285)
	at hudson.plugins.ec2.EC2Cloud.doProvision(EC2Cloud.java:283)
```

The same credentials work fine with the 1.8.3 version.

**Comment by nexus49** [comment]
adding below as proposed in https://forums.aws.amazon.com/thread.jspa?messageID=601048 fixes the issue for me: 

```
--- a/src/main/java/hudson/plugins/ec2/EC2Cloud.java
+++ b/src/main/java/hudson/plugins/ec2/EC2Cloud.java
@@ -474,6 +474,7 @@ public abstract class EC2Cloud extends Cloud {
     public synchronized static AmazonEC2 connect(AWSCredentialsProvider credentialsProvider, URL endpoint) {
         awsCredentialsProvider = credentialsProvider;
         ClientConfiguration config = new ClientConfiguration();
+        config.setSignerOverride("QueryStringSignerType");
         ProxyConfiguration proxyConfig = Jenkins.getInstance().proxy;
         Proxy proxy = proxyConfig == null ? Proxy.NO_PROXY : proxyConfig.createProxy(endpoint.getHost());
         if (! proxy.equals(Proxy.NO_PROXY) && proxy.address() instanceof InetSocketAddress) {
```

**Comment by cbek** [comment]
@nexus49 - Thanks!
Created a PR https://github.com/jenkinsci/ec2-plugin/pull/142

**Pull request merged**
