### PR TITLE
[JENKINS-25832] Launch multiple slaves in parallel for jobs with same node label

### PR DESCRIPTION
**Pull request by LuisPiedra**
When trying to provision a number of nodes for an excess workload greater than 1, when the plugin was checking if a new node was needed for the second and successive iterations, it was considering that no new instances were needed because there were nodes already starting. 

Added a list with the instances already considered in the excess workload loop, so they are no longer considered as usable to satisfy the excess workload.

### CODE REVIEW

**Comment by mcote55** [comment]
how do i get this code to patch my plugin?

**Comment by Jimilian** [comment]
@mcote55, you need to checkout https://github.com/LuisPiedra/ec2-plugin/tree/ExcessWorkload and execute `mvn clean install`

**Comment by vitalykarasik** [comment]
Any idea when/if which pathc will be merged to master?

**Comment by Jimilian** [comment]
@vitalykarasik, you can give a try to my PR as well: https://github.com/jenkinsci/ec2-plugin/pull/252. It contains working `.hpi` version.

@francisu and @johnnyshields can answer about merging stuff in master.

**Comment by bnf2si** [comment]
@Jimilian @LuisPiedra 
I tried both your implementation regarding launching multiple slaves in parallel.
But if I work this spot instances I have a problem. Calling getNewOrExistingAvailableSlave(...) in EC2Cloud.provision(...) does not return existing spot instances.
This leads to the effect that EC2Cloud.provision(...) launches too many instances, actually it doesn't stop launching until either 
a) the workload goes done - which is the case only when the newly launched instances are connected or
b) the maximum number of instances are launched (total or ami-specific)

Any idea?

**Comment by Jimilian** [comment]
@bnf2si please, provide some logs (example https://github.com/jenkinsci/ec2-plugin/pull/252#issuecomment-355061432 can help you to restore the picture). But in my implementation plugin returns existing instance if-and-only-if it was not known by current Jenkins instance. So, if Jenkins requests 100 nodes - plugin gives this 100 nodes. Jenkins takes care about number of pending instances in his `NodeProvisioner.DefaultStrategy`. If this strategy does not satisfy your needs (i.e. you want to keep number of nodes as small as possible or have bigger delay between provisioning attempts) you can play with system variables or implement your own strategy. Could be that you are using other strategy already? i.e. Kubernetes strategy (this one raises "instance" every time it has item in queue)?

**Comment by bnf2si** [comment]
@Jimilian Thanks for your quick reply.
A good hint which this strategy? Where can I set the Strategy, is there some documentation (Changing the delay between provisioning attempts I'd like to try ? In my binaries I have found only the `NodeProvisioner.StandardStrategyImpl' ( but I have only the code for the Ec2 plugin checked out including references binary stuff)

What I still wonder: Why do you call `findOrphans(diResult, number);` in  'SlaveTemplate.provisionOndemand(...)' but not in  'SlaveTemplate.provisionSpot(...) '

My logs
```
Attempting to provision slave from template hudson.plugins.ec2.SlaveTemplate@1f024dc9 needed by excess workload of 1 units of label 'test_spot'
Feb 28, 2018 7:04:56 AM INFO hudson.plugins.ec2.SlaveTemplate provisionSpot
Launching ami-b9bed3d6 for template Boa_Test
Feb 28, 2018 7:04:56 AM INFO hudson.plugins.ec2.EC2PrivateKey find
No key pair specified.
Feb 28, 2018 7:04:56 AM INFO hudson.plugins.ec2.SlaveTemplate getKeyPair
No matching keypair found on EC2. Is public key acquired via some other means?
Feb 28, 2018 7:04:56 AM INFO hudson.plugins.ec2.SlaveTemplate provisionSpot
Spot instance id in provision: sir-g7mijxgq
Feb 28, 2018 7:04:56 AM INFO hudson.plugins.ec2.EC2Cloud provision
We have now 2 computers
Feb 28, 2018 7:04:56 AM INFO hudson.plugins.ec2.EC2RetentionStrategy start
Start requested for Boa_Test-BH48cH54
Feb 28, 2018 7:04:56 AM INFO hudson.plugins.ec2.EC2Cloud provision
Added node named: Boa_Test-BH48cH54, We have now 3 computers
Feb 28, 2018 7:04:56 AM WARNING hudson.plugins.ec2.EC2Cloud$1 call
Expected - Instance - failed to connect within launch timeout
Feb 28, 2018 7:04:56 AM INFO hudson.plugins.ec2.EC2Cloud provision
Attempting provision - finished, excess workload: 0
Feb 28, 2018 7:04:56 AM INFO hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
Started provisioning Boa_Test (ami-b9bed3d6) from ec2-Boa with 1 executors. Remaining excess workload: 0
Feb 28, 2018 7:05:05 AM INFO hudson.slaves.NodeProvisioner$2 run
Boa_Test (ami-b9bed3d6) provisioning successfully completed. We have now 3 computer(s)
Feb 28, 2018 7:05:05 AM INFO hudson.plugins.ec2.EC2Cloud provision
Attempting to provision slave from template hudson.plugins.ec2.SlaveTemplate@1f024dc9 needed by excess workload of 1 units of label 'test_spot'
Feb 28, 2018 7:05:06 AM INFO hudson.plugins.ec2.SlaveTemplate provisionSpot
Launching ami-b9bed3d6 for template Boa_Test
Feb 28, 2018 7:05:06 AM INFO hudson.plugins.ec2.EC2PrivateKey find
No key pair specified.
Feb 28, 2018 7:05:06 AM INFO hudson.plugins.ec2.SlaveTemplate getKeyPair
No matching keypair found on EC2. Is public key acquired via some other means?
Feb 28, 2018 7:05:06 AM INFO hudson.plugins.ec2.SlaveTemplate provisionSpot
Spot instance id in provision: sir-df3ggkjm
Feb 28, 2018 7:05:06 AM INFO hudson.plugins.ec2.EC2Cloud provision
We have now 3 computers
Feb 28, 2018 7:05:06 AM INFO hudson.plugins.ec2.EC2RetentionStrategy start
Start requested for Boa_Test-3nvI8F1J
Feb 28, 2018 7:05:06 AM INFO hudson.plugins.ec2.EC2Cloud provision
Added node named: Boa_Test-3nvI8F1J, We have now 4 computers
Feb 28, 2018 7:05:06 AM WARNING hudson.plugins.ec2.EC2Cloud$1 call
Expected - Instance - failed to connect within launch timeout
Feb 28, 2018 7:05:06 AM INFO hudson.plugins.ec2.EC2Cloud provision
Attempting provision - finished, excess workload: 0
Feb 28, 2018 7:05:06 AM INFO hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
Started provisioning Boa_Test (ami-b9bed3d6) from ec2-Boa with 1 executors. Remaining excess workload: 0
Feb 28, 2018 7:05:15 AM INFO hudson.slaves.NodeProvisioner$2 run
Boa_Test (ami-b9bed3d6) provisioning successfully completed. We have now 4 computer(s)
Feb 28, 2018 7:05:15 AM INFO hudson.plugins.ec2.EC2Cloud provision
Attempting to provision slave from template hudson.plugins.ec2.SlaveTemplate@1f024dc9 needed by excess workload of 1 units of label 'test_spot'
Feb 28, 2018 7:05:16 AM INFO hudson.plugins.ec2.SlaveTemplate provisionSpot
Launching ami-b9bed3d6 for template Boa_Test
Feb 28, 2018 7:05:16 AM INFO hudson.plugins.ec2.EC2PrivateKey find
No key pair specified.
Feb 28, 2018 7:05:16 AM INFO hudson.plugins.ec2.SlaveTemplate getKeyPair
No matching keypair found on EC2. Is public key acquired via some other means?
Feb 28, 2018 7:05:17 AM INFO hudson.plugins.ec2.SlaveTemplate provisionSpot
Spot instance id in provision: sir-pvkghv5q
Feb 28, 2018 7:05:17 AM INFO hudson.plugins.ec2.EC2Cloud provision
We have now 4 computers
Feb 28, 2018 7:05:17 AM INFO hudson.plugins.ec2.EC2RetentionStrategy start
Start requested for Boa_Test-raKL1iPE
Feb 28, 2018 7:05:17 AM INFO hudson.plugins.ec2.EC2Cloud provision
Added node named: Boa_Test-raKL1iPE, We have now 5 computers
Feb 28, 2018 7:05:17 AM WARNING hudson.plugins.ec2.EC2Cloud$1 call
Expected - Instance - failed to connect within launch timeout
Feb 28, 2018 7:05:17 AM INFO hudson.plugins.ec2.EC2Cloud provision
Attempting provision - finished, excess workload: 0
Feb 28, 2018 7:05:17 AM INFO hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
Started provisioning Boa_Test (ami-b9bed3d6) from ec2-Boa with 1 executors. Remaining excess workload: 0
Feb 28, 2018 7:05:25 AM INFO hudson.slaves.NodeProvisioner$2 run
Boa_Test (ami-b9bed3d6) provisioning successfully completed. We have now 5 computer(s)
Feb 28, 2018 7:05:25 AM INFO hudson.plugins.ec2.EC2Cloud provision
Attempting to provision slave from template hudson.plugins.ec2.SlaveTemplate@1f024dc9 needed by excess workload of 1 units of label 'test_spot'
```

**Comment by Jimilian** [comment]
@bnf2si you need to check `calcThresholdMargin` in this case (`MARGIN` is a system property defined ~30 lines below the function).
but based on your logs I can see the error:
`Expected - Instance - failed to connect within launch timeout`

It means that from Jenkins perspective instance did not appear -> it tries to raise new one.
Also take a look in
```
Feb 28, 2018 7:05:16 AM INFO hudson.plugins.ec2.EC2PrivateKey find
No key pair specified.
Feb 28, 2018 7:05:16 AM INFO hudson.plugins.ec2.SlaveTemplate getKeyPair
No matching keypair found on EC2. Is public key acquired via some other means?
```

**Comment by bnf2si** [comment]
thanks a lot @Jimilian for you help!
After some modifications it works now :-)

I really like you approach of launch multiple slaves in parallel ( https://github.com/jenkinsci/ec2-plugin/pull/252 ).
Took you branch as a new base and build our changes on top it:
https://github.com/bnf2si/ec2-plugin/releases/tag/v1.39-alpha2

We will test our changes now (related to "self-connecting windows agents) and after your changes - hopefully - get merged into the main project, I will create a pull request for my changes as well.

**Comment by bnf2si** [comment]
@Jimilian 
I started working on supporting **stopping of spot instances** as well instead of always terminating them.
Here a very first impl:
https://github.com/bnf2si/ec2-plugin/blob/ec2_katysha_edition_mergedWithUs/src/main/java/hudson/plugins/ec2/SlaveTemplate.java#L794

I have to test the behavior of that feature next week.

If that works in general, it makes send to completely refactor `SlaveTemplate.provisionOndemand` and  `SlaveTemplate.provisionSpot` because they get more and more similar.

**Comment by thoulen** [comment]
I am expecting the pr-252 resolved the problem can I close this pull request ?

**Comment by LuisPiedra** [comment]
Should be solved now with new algorithm in version 1.40

**Pull request closed without merging**
