### PR TITLE
Fix the "Check AMI" and "Check Current Spot Price" buttons

### PR DESCRIPTION
**Pull request by cyrille-leclerc**
Fix the "Check AMI" and "Check Current Spot Price" buttons

Fixed buttons

### CODE REVIEW

**Comment by johnnyshields** [comment]
:+1:

**Comment by johnnyshields** [comment]
@francisu let's merge and release :)

**Comment by francisu** [comment]
OK will release later tonight my time.

**Comment by johnnyshields** [comment]
@cyrille-leclerc thanks!!

**Comment by cyrille-leclerc** [comment]
Thanks @johnnyshields !

**Pull request merged**
